apply from: "../build.common.gradle"
android {
    namespace = 'org.firstinspires.ftc.teamcode'
}

buildscript {
    repositories {
        mavenCentral()
        maven { url "https://repo.dairy.foundation/releases" }
    }
    dependencies { classpath "dev.frozenmilk:Load:0.1.0" }
}
apply plugin: "dev.frozenmilk.sinister.sloth.load"
